<h1> N Karthik (4178520) </h1>
<h1> Alfin Abraham (4181788) </h1>


# TW1

## Pandas Series and DataFrame

- Practice Pandas Series and DataFrame with examples.

#### Write full names of your team members who worked together.




#### Submission:

- Push the completed code to your Github repository.

## Part 0

Practice Pandas Series and DataFrame with the given examples.

In [107]:
import pandas as pd

In [108]:
alist = ['Mouse', 'Giraffe', 'Tiger', 'Dog', 'Hippopotamus', 'Moose', 'Bear']
animals = pd.Series(alist)
animals

0           Mouse
1         Giraffe
2           Tiger
3             Dog
4    Hippopotamus
5           Moose
6            Bear
dtype: object

In [109]:
animals[2]

'Tiger'

In [110]:
animals.iloc[2]

'Tiger'

In [111]:
animals.loc[2]

'Tiger'

In [112]:
s1 = pd.Series(alist, index=[0, 1, 2, 3, 4, 5, 6])
s1

0           Mouse
1         Giraffe
2           Tiger
3             Dog
4    Hippopotamus
5           Moose
6            Bear
dtype: object

In [113]:
s2 = pd.Series(alist, index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])
s2

a           Mouse
b         Giraffe
c           Tiger
d             Dog
e    Hippopotamus
f           Moose
g            Bear
dtype: object

In [114]:
s2['c']

'Tiger'

In [115]:
s2.loc['c']

'Tiger'

In [116]:
s2.iloc[2]

'Tiger'

In [117]:
names = ['Chris', 'Kevin', 'Bob', 'Vinod', 'Daniel', 'Fil', 'Stephanie']
owners = pd.Series(names)
owners

0        Chris
1        Kevin
2          Bob
3        Vinod
4       Daniel
5          Fil
6    Stephanie
dtype: object

In [118]:
frame = {'animals': animals, 'owners': owners}

df = pd.DataFrame(frame)

df

        animals     owners
0         Mouse      Chris
1       Giraffe      Kevin
2         Tiger        Bob
3           Dog      Vinod
4  Hippopotamus     Daniel
5         Moose        Fil
6          Bear  Stephanie

In [119]:
df.columns

Index(['animals', 'owners'], dtype='object')

In [120]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [121]:
type(df['animals'])

pandas.core.series.Series

In [122]:
df.iloc[0]

animals    Mouse
owners     Chris
Name: 0, dtype: object

In [123]:
df.loc[0][1]

'Chris'

In [124]:
# copy an existing DataFrame to create a new dataFrame
copy_df = df.copy()
copy_df

        animals     owners
0         Mouse      Chris
1       Giraffe      Kevin
2         Tiger        Bob
3           Dog      Vinod
4  Hippopotamus     Daniel
5         Moose        Fil
6          Bear  Stephanie

In [125]:
# drop columns

df2 = df.drop(['owners'], axis = 1)

df2

        animals
0         Mouse
1       Giraffe
2         Tiger
3           Dog
4  Hippopotamus
5         Moose
6          Bear

In [126]:
# drop columns

df3 = df.drop(columns = ['owners'])

df3

        animals
0         Mouse
1       Giraffe
2         Tiger
3           Dog
4  Hippopotamus
5         Moose
6          Bear

In [127]:
# drop rows

df4 = df.drop([0,1])
df4

        animals     owners
2         Tiger        Bob
3           Dog      Vinod
4  Hippopotamus     Daniel
5         Moose        Fil
6          Bear  Stephanie

In [128]:
midx = pd.MultiIndex(levels=[['lama', 'cow', 'falcon'],
                             ['speed', 'weight']],
                     codes=[[0, 0, 1, 1, 2, 2],
                            [0, 1, 0, 1, 0, 1]])

midx

MultiIndex([(  'lama',  'speed'),
            (  'lama', 'weight'),
            (   'cow',  'speed'),
            (   'cow', 'weight'),
            ('falcon',  'speed'),
            ('falcon', 'weight')],
           )

In [129]:
df = pd.DataFrame(index=midx, columns=['big', 'small'],
                   data=[[45, 30], [200, 100], [30, 20], [250, 150], [320, 250],[1, 0.8]])

df

               big  small
lama   speed    45   30.0
       weight  200  100.0
cow    speed    30   20.0
       weight  250  150.0
falcon speed   320  250.0
       weight    1    0.8

In [130]:
df.drop(index='cow', columns='small')

               big
lama   speed    45
       weight  200
falcon speed   320
       weight    1

In [131]:
df.drop(index='weight', level=1)

              big  small
lama   speed   45   30.0
cow    speed   30   20.0
falcon speed  320  250.0

## Part 1 Task 1

Given the data below, implement each tasks. 

<img src="img/df.png" style="height:200px"> 

(1) Create a DataFrame.

(2) Access the first row data and print it.

(3) Access the first column data (indexed by 'dept') and print it.

(4) Create a new DataFrame by dropping the 2nd column data (indexed by 'floor') from the current DataFrame.

In [132]:
import pandas as pd
list = ["CS", "Bio", "Chem","Phy","Eng"]
dept = pd.Series(list)
list2 = ["5","3","3","2","4"] 
floor=pd.Series(list2)
fr = {"dept":dept, "floor":floor}
df= pd.DataFrame(fr)
df

   dept floor
0    CS     5
1   Bio     3
2  Chem     3
3   Phy     2
4   Eng     4

In [133]:
df.iloc[0]

dept     CS
floor     5
Name: 0, dtype: object

In [134]:
df.dept

0      CS
1     Bio
2    Chem
3     Phy
4     Eng
Name: dept, dtype: object

In [135]:
df1 = df.drop(columns = 'dept')
df1

  floor
0     5
1     3
2     3
3     2
4     4

## Part 1 Task 2

Practice with a data file. 

(1) Choose one data file from the data folder in the given TW1 folder.

(2) Read the data into a DataFrame. 

(3) Access the rows and columns. 

(4) Drop some columns.

In [136]:
pd.read_csv("cars.csv")

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
0,2012,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
1,2012,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
2,2013,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
3,2013,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
4,2013,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
5,2013,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
6,2013,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
7,2013,TESLA,MODEL S (40 kWh battery),FULL-SIZE,270,A1,B,22.4,21.9,22.2,2.5,2.5,2.5,0,NaN,224,6
8,2013,TESLA,MODEL S (60 kWh battery),FULL-SIZE,270,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
9,2013,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
10,2013,TESLA,MODEL S PERFORMANCE,FULL-SIZE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
11,2014,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
12,2014,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
13,2014,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
14,2014,NISSAN,LEAF,MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,NaN,135,5
15,2014,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
16,2014,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
17,2014,TESLA,MODEL S (60 kWh battery),FULL-SIZE,225,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
18,2014,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
19,2014,TESLA,MODEL S PERFORMANCE,FULL-SIZE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
20,2015,BMW,i3,SUBCOMPACT,125,A1,B,15.2,18.8,16.8,1.7,2.1,1.9,0,NaN,130,4
21,2015,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
22,2015,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
23,2015,KIA,SOUL EV,STATION WAGON - SMALL,81,A1,B,17.5,22.7,19.9,2.0,2.6,2.2,0,NaN,149,4
24,2015,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
25,2015,NISSAN,LEAF,MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,NaN,135,5
26,2015,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
27,2015,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
28,2015,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
29,2015,TESLA,MODEL S (70 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,377,12
30,2015,TESLA,MODEL S (85/90 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
31,2015,TESLA,MODEL S 70D,FULL-SIZE,280,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,NaN,386,12
32,2015,TESLA,MODEL S 85D/90D,FULL-SIZE,280,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,NaN,435,12
33,2015,TESLA,MODEL S P85D/P90D,FULL-SIZE,515,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,NaN,407,12
34,2016,BMW,i3,SUBCOMPACT,125,A1,B,15.2,18.8,16.8,1.7,2.1,1.9,0,10.0,130,4
35,2016,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,10.0,131,7
36,2016,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,10.0,122,4
37,2016,KIA,SOUL EV,STATION WAGON - SMALL,81,A1,B,17.5,22.7,19.9,2.0,2.6,2.2,0,10.0,149,4
38,2016,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,10.0,100,7
39,2016,NISSAN,LEAF (24 kWh battery),MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,10.0,135,5
40,2016,NISSAN,LEAF (30 kWh battery),MID-SIZE,80,A1,B,17.0,20.7,18.6,1.9,2.3,2.1,0,10.0,172,6
41,2016,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,10.0,109,8
42,2016,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,10.0,109,8
43,2016,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,10.0,335,10
44,2016,TESLA,MODEL S (70 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,377,12
45,2016,TESLA,MODEL S (85/90 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,426,12
46,2016,TESLA,MODEL S 70D,FULL-SIZE,386,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,10.0,386,12
47,2016,TESLA,MODEL S 85D/90D,FULL-SIZE,386,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,10.0,435,12
48,2016,TESLA,MODEL S 90D (Refresh),FULL-SIZE,386,A1,B,20.8,19.7,20.3,2.3,2.2,2.3,0,10.0,473,12
49,2016,TESLA,MODEL S P85D/P90D,FULL-SIZE,568,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,10.0,407,12
50,2016,TESLA,MODEL S P90D (Refresh),FULL-SIZE,568,A1,B,22.9,21.0,22.1,2.6,2.4,2.5,0,10.0,435,12
51,2016,TESLA,MODEL X 90D,SUV - STANDARD,386,A1,B,23.2,22.2,22.7,2.6,2.5,2.6,0,10.0,414,12
52,2016,TESLA,MODEL X P90D,SUV - STANDARD,568,A1,B,23.6,23.3,23.5,2.7,2.6,2.6,0,10.0,402,12

In [137]:
df=pd.read_csv("cars.csv")
df

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
0,2012,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
1,2012,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
2,2013,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
3,2013,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
4,2013,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
5,2013,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
6,2013,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
7,2013,TESLA,MODEL S (40 kWh battery),FULL-SIZE,270,A1,B,22.4,21.9,22.2,2.5,2.5,2.5,0,NaN,224,6
8,2013,TESLA,MODEL S (60 kWh battery),FULL-SIZE,270,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
9,2013,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
10,2013,TESLA,MODEL S PERFORMANCE,FULL-SIZE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
11,2014,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
12,2014,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
13,2014,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
14,2014,NISSAN,LEAF,MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,NaN,135,5
15,2014,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
16,2014,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
17,2014,TESLA,MODEL S (60 kWh battery),FULL-SIZE,225,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
18,2014,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
19,2014,TESLA,MODEL S PERFORMANCE,FULL-SIZE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
20,2015,BMW,i3,SUBCOMPACT,125,A1,B,15.2,18.8,16.8,1.7,2.1,1.9,0,NaN,130,4
21,2015,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
22,2015,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
23,2015,KIA,SOUL EV,STATION WAGON - SMALL,81,A1,B,17.5,22.7,19.9,2.0,2.6,2.2,0,NaN,149,4
24,2015,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
25,2015,NISSAN,LEAF,MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,NaN,135,5
26,2015,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
27,2015,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
28,2015,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
29,2015,TESLA,MODEL S (70 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,377,12
30,2015,TESLA,MODEL S (85/90 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
31,2015,TESLA,MODEL S 70D,FULL-SIZE,280,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,NaN,386,12
32,2015,TESLA,MODEL S 85D/90D,FULL-SIZE,280,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,NaN,435,12
33,2015,TESLA,MODEL S P85D/P90D,FULL-SIZE,515,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,NaN,407,12
34,2016,BMW,i3,SUBCOMPACT,125,A1,B,15.2,18.8,16.8,1.7,2.1,1.9,0,10.0,130,4
35,2016,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,10.0,131,7
36,2016,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,10.0,122,4
37,2016,KIA,SOUL EV,STATION WAGON - SMALL,81,A1,B,17.5,22.7,19.9,2.0,2.6,2.2,0,10.0,149,4
38,2016,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,10.0,100,7
39,2016,NISSAN,LEAF (24 kWh battery),MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,10.0,135,5
40,2016,NISSAN,LEAF (30 kWh battery),MID-SIZE,80,A1,B,17.0,20.7,18.6,1.9,2.3,2.1,0,10.0,172,6
41,2016,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,10.0,109,8
42,2016,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,10.0,109,8
43,2016,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,10.0,335,10
44,2016,TESLA,MODEL S (70 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,377,12
45,2016,TESLA,MODEL S (85/90 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,426,12
46,2016,TESLA,MODEL S 70D,FULL-SIZE,386,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,10.0,386,12
47,2016,TESLA,MODEL S 85D/90D,FULL-SIZE,386,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,10.0,435,12
48,2016,TESLA,MODEL S 90D (Refresh),FULL-SIZE,386,A1,B,20.8,19.7,20.3,2.3,2.2,2.3,0,10.0,473,12
49,2016,TESLA,MODEL S P85D/P90D,FULL-SIZE,568,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,10.0,407,12
50,2016,TESLA,MODEL S P90D (Refresh),FULL-SIZE,568,A1,B,22.9,21.0,22.1,2.6,2.4,2.5,0,10.0,435,12
51,2016,TESLA,MODEL X 90D,SUV - STANDARD,386,A1,B,23.2,22.2,22.7,2.6,2.5,2.6,0,10.0,414,12
52,2016,TESLA,MODEL X P90D,SUV - STANDARD,568,A1,B,23.6,23.3,23.5,2.7,2.6,2.6,0,10.0,402,12

In [138]:
df.loc[0]

YEAR                       2012
Make                 MITSUBISHI
Model                    i-MiEV
Size                 SUBCOMPACT
(kW)                         49
Unnamed: 5                   A1
TYPE                          B
CITY (kWh/100 km)          16.9
HWY (kWh/100 km)           21.4
COMB (kWh/100 km)          18.7
CITY (Le/100 km)            1.9
HWY (Le/100 km)             2.4
COMB (Le/100 km)            2.1
(g/km)                        0
RATING                      NaN
(km)                        100
TIME (h)                      7
Name: 0, dtype: object

In [139]:
df['Make']

0     MITSUBISHI
1         NISSAN
2           FORD
3     MITSUBISHI
4         NISSAN
5          SMART
6          SMART
7          TESLA
8          TESLA
9          TESLA
10         TESLA
11     CHEVROLET
12          FORD
13    MITSUBISHI
14        NISSAN
15         SMART
16         SMART
17         TESLA
18         TESLA
19         TESLA
20           BMW
21     CHEVROLET
22          FORD
23           KIA
24    MITSUBISHI
25        NISSAN
26         SMART
27         SMART
28         TESLA
29         TESLA
30         TESLA
31         TESLA
32         TESLA
33         TESLA
34           BMW
35     CHEVROLET
36          FORD
37           KIA
38    MITSUBISHI
39        NISSAN
40        NISSAN
41         SMART
42         SMART
43         TESLA
44         TESLA
45         TESLA
46         TESLA
47         TESLA
48         TESLA
49         TESLA
50         TESLA
51         TESLA
52         TESLA
Name: Make, dtype: object

In [143]:
df.drop(['YEAR', 'Make','Size'],axis=1)

,Model,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
0,i-MiEV,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
1,LEAF,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
2,FOCUS ELECTRIC,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
3,i-MiEV,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
4,LEAF,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
5,FORTWO ELECTRIC DRIVE CABRIOLET,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
6,FORTWO ELECTRIC DRIVE COUPE,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
7,MODEL S (40 kWh battery),270,A1,B,22.4,21.9,22.2,2.5,2.5,2.5,0,NaN,224,6
8,MODEL S (60 kWh battery),270,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
9,MODEL S (85 kWh battery),270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
10,MODEL S PERFORMANCE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
11,SPARK EV,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
12,FOCUS ELECTRIC,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
13,i-MiEV,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
14,LEAF,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,NaN,135,5
15,FORTWO ELECTRIC DRIVE CABRIOLET,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
16,FORTWO ELECTRIC DRIVE COUPE,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
17,MODEL S (60 kWh battery),225,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
18,MODEL S (85 kWh battery),270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
19,MODEL S PERFORMANCE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
20,i3,125,A1,B,15.2,18.8,16.8,1.7,2.1,1.9,0,NaN,130,4
21,SPARK EV,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
22,FOCUS ELECTRIC,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
23,SOUL EV,81,A1,B,17.5,22.7,19.9,2.0,2.6,2.2,0,NaN,149,4
24,i-MiEV,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
25,LEAF,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,NaN,135,5
26,FORTWO ELECTRIC DRIVE CABRIOLET,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
27,FORTWO ELECTRIC DRIVE COUPE,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
28,MODEL S (60 kWh battery),283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
29,MODEL S (70 kWh battery),283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,377,12
30,MODEL S (85/90 kWh battery),283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
31,MODEL S 70D,280,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,NaN,386,12
32,MODEL S 85D/90D,280,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,NaN,435,12
33,MODEL S P85D/P90D,515,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,NaN,407,12
34,i3,125,A1,B,15.2,18.8,16.8,1.7,2.1,1.9,0,10.0,130,4
35,SPARK EV,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,10.0,131,7
36,FOCUS ELECTRIC,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,10.0,122,4
37,SOUL EV,81,A1,B,17.5,22.7,19.9,2.0,2.6,2.2,0,10.0,149,4
38,i-MiEV,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,10.0,100,7
39,LEAF (24 kWh battery),80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,10.0,135,5
40,LEAF (30 kWh battery),80,A1,B,17.0,20.7,18.6,1.9,2.3,2.1,0,10.0,172,6
41,FORTWO ELECTRIC DRIVE CABRIOLET,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,10.0,109,8
42,FORTWO ELECTRIC DRIVE COUPE,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,10.0,109,8
43,MODEL S (60 kWh battery),283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,10.0,335,10
44,MODEL S (70 kWh battery),283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,377,12
45,MODEL S (85/90 kWh battery),283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,426,12
46,MODEL S 70D,386,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,10.0,386,12
47,MODEL S 85D/90D,386,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,10.0,435,12
48,MODEL S 90D (Refresh),386,A1,B,20.8,19.7,20.3,2.3,2.2,2.3,0,10.0,473,12
49,MODEL S P85D/P90D,568,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,10.0,407,12
50,MODEL S P90D (Refresh),568,A1,B,22.9,21.0,22.1,2.6,2.4,2.5,0,10.0,435,12
51,MODEL X 90D,386,A1,B,23.2,22.2,22.7,2.6,2.5,2.6,0,10.0,414,12
52,MODEL X P90D,568,A1,B,23.6,23.3,23.5,2.7,2.6,2.6,0,10.0,402,12